name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2PRIVKEY }}
            HOSTNAME: ${{secrets.EC2DNS}}
            USER_NAME: ${secrets.EC2USERNAME}
      
        run: |
          echo "$PRIVATE_KEY" > coordinote.pem && chmod 400 coordinote.pem
          ssh -i coordinote ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /~/coordinote &&
              git checkout dev &&
              git fetch --all &&
              git reset --hard origin/dev &&
              git pull origin dev &&
              sudo npm i &&
              sudo npm run install:client &&
              sudo npm run install:server &&
              sudo npm run build:client &&
              sudo pm2 stop ./server/app.js &&
              sudo pm2 start ./server/app.js
              '
